### ISSUE TITLE
How to fetch statename with spaces?

### ISSUE THREAD

**Issue by AbhinavMir** [HrithikMittal/COVID19-India-API#2]
For the route "[https://covid19-india-adhikansh.herokuapp.com/states/](https://covid19-india-adhikansh.herokuapp.com/states/)", how do I fetch result for any state with space in the name, eg "Andhra Pradesh".

**Comment by HrithikMittal** [comment]
Use with space only. It will automatically be converted to ASCII value %20.
https://covid19-india-adhikansh.herokuapp.com/state/Andhra%20Pradesh

**Comment by AbhinavMir** [comment]
Thanks, closing.
