### ISSUE TITLE
Discrepancy in data

### ISSUE THREAD

**Issue by pulkit-rastogi97** [HrithikMittal/COVID19-India-API#3]
I have observed that there is discrepancy in the data you api is returning as a response.
Currently, there are more than 53k+ total cases. but it is showing about 37k, you can check out the source of your data as well. It is correct but your api's data is having discrepancy.
![image](https://user-images.githubusercontent.com/61677254/81333440-40984e80-90c2-11ea-9d36-f390e7b57023.png)

**Comment by HrithikMittal** [comment]
Thank you for the update.
The website is changed so I have to make some little bit changes in the script.
Now API's are working fine you can check it out.

**Comment by pulkit-rastogi97** [comment]
Yes, It is working better. But the field "Total Cases" is still having an error. because till date the cases are approaching 53k and not 70k, a small logica error : it is adding up all the fields, it should not.

**Comment by HrithikMittal** [comment]
Ya, I created it in such a way it's just a small logic error.
