### ISSUE TITLE
Data not updated as per the current status in MOHFW.org in /states/.

### ISSUE THREAD

**Issue by hrshtpnt** [HrithikMittal/COVID19-India-API#7]
Report is not showing correct data, when does the data update happens?

I have observed that there is discrepancy in the data the api /states/ is returning as a response.

**Comment by HrithikMittal** [comment]
Hey, @hrshtpnt as there are some changes in mohfw website day before yesterday so I have to change my script for scraping the data. That's why you get the difference in data. It will work accurately from tmw. and data is updated daily at 6:00 p.m.

**Comment by HrithikMittal** [comment]
Bug fixes.

**Comment by hrshtpnt** [comment]
@HrithikMittal Thanks a lot. I think it works but confirmed key seems changed to active.

**Comment by HrithikMittal** [comment]
Ya right, now Confirmed changes to activd cases and total cases directly come from the website previously it was calculated in the program.

**Comment by hrshtpnt** [comment]
The data is still not updating. I think its showing the old data. Not updating based on the MOHFW.org

**Comment by HrithikMittal** [comment]
It is updating on MOHFW only but for every day it will update at 6:00 p.m.

**Comment by HrithikMittal** [comment]
So the data which is updated on the official website will be updated at 6:00 p.m. today
